<?php

namespace api\modules\v1\controllers;

use yii\rest\ActiveController;
use yii\helpers\ArrayHelper;

class CompanyDetailController extends ActiveController
{
    public $modelClass = 'api\modules\v1\models\CompanyDetail';    

	public function actions()
    {
        $action= parent::actions();//TODO: Change the autogenerated stub
        unset($action['company']);
        return $action;
    }

	public function actionCompany($id) {
        return ArrayHelper::map($this->modelClass::find()->where(['company'=>$id])->asArray()->all(), 'id', 'payment_tnc');
	}
}
